# Generated by Django 4.0.2 on 2022-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=50)),
                ('instance_name_connection', models.CharField(max_length=50)),
                ('instance_credential', models.CharField(max_length=50)),
            ],
        ),
    ]
