# Generated by Django 4.0.2 on 2022-03-03 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cred_name', models.CharField(max_length=20)),
                ('cred_type', models.CharField(max_length=50)),
                ('cred_ssh_private_key', models.CharField(default=' ', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ManagedNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=50)),
                ('instance_name_connection', models.CharField(max_length=50)),
                ('instance_credential', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
