# Generated by Django 4.0.2 on 2022-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cred_name', models.CharField(max_length=20)),
                ('cred_type', models.CharField(max_length=50)),
                ('instance_credential', models.CharField(max_length=50)),
            ],
        ),
    ]
