# Generated by Django 4.0.2 on 2022-03-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='instance_credential',
        ),
        migrations.AddField(
            model_name='credentials',
            name='cred_ssh_private_key',
            field=models.CharField(default=' ', max_length=5000),
        ),
    ]
