# Generated by Django 4.0.2 on 2022-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_incidents_incident_time_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_output_fields',
            field=models.JSONField(),
        ),
    ]
