# Generated by Django 4.0.2 on 2022-03-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_incidents_incident_output_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='incident_output_fields_new',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='incident_output_fields',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
