# Generated by Django 4.0.2 on 2022-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_incidents_incident_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_rule',
            field=models.CharField(default='', max_length=200),
        ),
    ]
