# Generated by Django 4.0.2 on 2022-03-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_incidents_incident_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='incident_fix_comments',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='incidents',
            name='incident_status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='incidents',
            name='incident_time_fixed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
