# Generated by Django 4.0.2 on 2022-03-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_incidents_incident_fix_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_time_fixed',
            field=models.DateTimeField(),
        ),
    ]
