# Generated by Django 4.0.2 on 2022-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_incidents_incident_time_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_time_fixed',
            field=models.DateTimeField(default=None),
        ),
    ]
