# Generated by Django 4.0.2 on 2022-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='cred_ssh_password',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='credentials',
            name='cred_ssh_user_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
