# Generated by Django 4.0.2 on 2022-03-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_credentials_cred_ssh_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managednodes',
            name='instance_credential_to_use',
            field=models.CharField(default='Username-Password', max_length=50),
        ),
    ]
