# Generated by Django 4.0.2 on 2022-03-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_managednodes_instance_credential_to_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managednodes',
            name='instance_credential_to_use',
        ),
    ]
