# Generated by Django 4.0.2 on 2022-03-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_managednodes_instance_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managednodes',
            name='instance_credential',
            field=models.CharField(default='---', max_length=50),
        ),
    ]
