# Generated by Django 4.0.3 on 2022-03-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_credentials_cred_ssh_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=50, unique=True)),
                ('token_desc', models.CharField(max_length=100)),
                ('token_value', models.CharField(max_length=50)),
            ],
        ),
    ]
