# Generated by Django 4.0.3 on 2022-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='token_value',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
